### ISSUE TITLE
Docs website is not accessible

### ISSUE THREAD

**Issue by WaldemarEnns** [MartinMalinda/vue-concurrency#11]
# Problem

The page, which the link in the [README.md](https://github.com/MartinMalinda/vue-concurrency/blob/master/README.md) file refers to as the documatation, is not working:

* https://vue-concurrency.netlify.app/

## How to reproduce

* Visit this link: https://vue-concurrency.netlify.app/
* Or try to go to the page via the [README.md](https://github.com/MartinMalinda/vue-concurrency/blob/master/README.md) file

## Solution proposal

I don't know - I would be happy if the docs-page would work! :)

**Comment by MartinMalinda** [comment]
Huh, thanks for reporting @WaldemarEnns ! It's working for me but I'm investigating. Any info about your OS / Browser would be appreciated.

**Comment by WaldemarEnns** [comment]
@MartinMalinda 

**Browser and OS**:
```
Google Chrome | 83.0.4103.116 (Official Build) (64-Bit)
OS | macOS Version 10.15.4 (Build 19E287)
```

**Screenshot**:
![Bildschirmfoto 2020-07-06 um 13 43 47](https://user-images.githubusercontent.com/43604224/86589860-bae43280-bf8e-11ea-9db9-41427ee6e8e6.png)

![Bildschirmfoto 2020-07-06 um 13 44 58](https://user-images.githubusercontent.com/43604224/86589963-e8c97700-bf8e-11ea-95c0-7e3141511085.png)

**Comment by MartinMalinda** [comment]
It could be some kind of SSL issue with Netlify I suppose. I reported it further and I hope I'll get some answers. Thanks a lot for the report.

Meanwhile I guess some kind of proxy could help... or cloning this repo and running `npm install && npm run docs:dev` :)

**Comment by WaldemarEnns** [comment]
@MartinMalinda Your'e welcome! Thanks for the great repo! :)

I have cloned the repo and started the docs in dev mode already 👍

**Comment by MartinMalinda** [comment]
Apparently it was a temporary issue an it should be fixed by now:

https://community.netlify.com/t/site-not-accessible-for-certain-users-http-vue-concurrency-netlify-app/18264/3

**Comment by WaldemarEnns** [comment]
Thanks for the information!
Currently it is still not available for me, I will check it again in the evening 👍

**Comment by MartinMalinda** [comment]
Huh, on the community forums they say it should be fine, but I'll keep this open just in case someone else experiences this.

**Comment by MartinMalinda** [comment]
Closing. Let's hope it was some rare Netlify glitch that won't happen again.
